name: Run Minervini Stock Screener

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 22 * * 1-5' 

jobs:
  run-screener:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the screener
        run: python screener.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "prafulsuthar101@gmail.com"
          git config --local user.name "Praful Suthar"
          git add README.md
          # Commit only if there are changes
          if ! git diff --staged --quiet; then
            git pull --rebase
            git commit -m "Automated screener results update for $(date -u +'%Y-%m-%d')"
            git push
          else
            echo "No changes to commit."
          fi
